version: '3.8'

services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
  redis_wui:
    container_name: redis_commander
    hostname: redis-wui
    image: ghcr.io/joeferner/redis-commander:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
  be_dev_proxy:
    container_name: be_dev_proxy
    hostname: be_dev_proxy
    image: nginx
    restart: unless-stopped
    volumes:
      - "./data/nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./data/nginx/certs/:/etc/ssl/private"
    network_mode: host
