version: '3.8'

services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
  redis_wui:
    container_name: redis_commander
    hostname: redis-wui
    image: ghcr.io/joeferner/redis-commander:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
  be_dev_proxy:
    container_name: be_dev_proxy
    hostname: be_dev_proxy
    image: nginx
    restart: unless-stopped
    volumes:
      - "./data/nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./data/nginx/certs/:/etc/ssl/private"
    network_mode: host
  rmq:
    container_name: hipnos_rmq
    hostname: hipnos_rmq  # This is important. Otherwise, rmq will recreate data folder and will be empty
    restart: unless-stopped
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"    # RMQ itself
      - "15672:15672"  # Web console
    volumes:
      - ./data/rmq/data/:/var/lib/rabbitmq/
