# Generated by Django 4.2.1 on 2023-05-09 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'hipnos_memory_type',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(default='', max_length=255)),
                ('unlocked_at', models.DateTimeField(null=True)),
                ('markdown_text', models.TextField(default='')),
                ('html_text', models.TextField(default='')),
                ('order_key', models.IntegerField()),
                ('memory_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hipnos.memorytype')),
            ],
        ),
    ]
