# Generated by Django 4.2.1 on 2023-05-11 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hipnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HipnosPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('phrase', models.CharField(max_length=255, unique=True)),
                ('unlocked_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'hipnos_phrase',
            },
        ),
        migrations.CreateModel(
            name='HProgramState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'hipnos_program_state',
            },
        ),
        migrations.CreateModel(
            name='HipnosProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(default='', max_length=255, null=True)),
                ('code_part', models.CharField(max_length=2)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hipnos.hprogramstate')),
                ('target_phrase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hipnos.hipnosphrase')),
            ],
            options={
                'db_table': 'hipnos_program',
            },
        ),
        migrations.AddField(
            model_name='hipnosphrase',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hipnos.hipnosprogram'),
        ),
        migrations.AddField(
            model_name='hipnosphrase',
            name='synonym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hipnos.hipnosphrase'),
        ),
    ]
