# Generated by Django 4.2.1 on 2023-05-11 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hipnos', '0002_program_subsytem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hipnosphrase',
            name='synonym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hipnos.hipnosphrase'),
        ),
    ]
