# Generated by Django 4.2.1 on 2023-05-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipnos', '0005_auto_generate_order_for_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hipnosprogram',
            name='order_key',
            field=models.IntegerField(),
        ),
    ]
