# Generated by Django 4.2.1 on 2023-05-13 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hipnos', '0008_phraseaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hipnosprogram',
            name='target_phrase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hipnos.hipnosphrase'),
        ),
    ]
