# Generated by Django 4.2.1 on 2023-05-14 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('hipnos', '0010_heventtype_hipnosevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.IntegerField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationchannel')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hipnos.heventtype')),
            ],
            options={
                'db_table': 'hipnos_event_notification',
            },
        ),
    ]
