# Generated by Django 4.2.1 on 2023-05-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipnos', '0011_eventnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='is_lore',
            field=models.BooleanField(default=True),
        ),
    ]
