# Generated by Django 4.2.1 on 2023-06-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0002_defaultuserpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synergytab',
            name='name',
        ),
        migrations.AlterField(
            model_name='synergytab',
            name='display_name',
            field=models.CharField(default='Виджет', max_length=255),
        ),
        migrations.AlterField(
            model_name='synergytab',
            name='widget_args',
            field=models.JSONField(default=dict),
        ),
    ]
