# Generated by Django 4.2.1 on 2023-06-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0003_remove_synergytab_name_alter_synergytab_display_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(default='', max_length=255)),
                ('fields', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'synergy_tab_type',
            },
        ),
    ]
