# Generated by Django 4.2.1 on 2023-07-31 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0005_synergytab_tab_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='synergytab',
            old_name='widget_args',
            new_name='widget_state',
        ),
    ]
