# Generated by Django 4.2.1 on 2023-08-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0006_rename_widget_args_synergytab_widget_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='synergytab',
            name='is_initialized',
            field=models.BooleanField(default=False),
        ),
    ]
